### ISSUE TITLE
Merging AES keys is not working

### ISSUE THREAD

**Issue by Perflyst** [jaiswalvik/aes-256-key-split-merge-utility#1]
I tried to merge two keys
`java -jar key-split-merge-util.jar mergeKeys 8e3c9efe64ec35fab42fe1a009701aee3fc47decd2c61ea3e29dfeaf8c4efc86 00fba8989f65a1a7234cde6b5f3340d689a81ce86c4a69d30009026dcc74a76e
`
```

Exception in thread "main" java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: e
        at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:248)
        at com.wecanendcraving.encryption.MainApp.main(MainApp.java:47)
Caused by: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: e
        at com.google.common.io.BaseEncoding$Alphabet.decode(BaseEncoding.java:543)
        at com.google.common.io.BaseEncoding$StandardBaseEncoding$2.read(BaseEncoding.java:715)
        at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:265)
        at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:246)
        ... 1 more
```

**Comment by jaiswalvik** [comment]
please run the test....you will see all the operations being performed correctly.

**Comment by Perflyst** [comment]
I can see that the tests succeed, yes. But that does not show me why I cannot merge these two AES256 Keys. I also tried with the uppercase variant

```
$ java -jar key-split-merge-util.jar mergeKeys 8E3C9EFE64EC35FAB42FE1A009701AEE3FC47DECD2C61EA3E29DFEAF8C4EFC86 00FBA8989F65A1A7234CDE6B5F3340D689A81CE86C4A69D30009026DCC74A76E
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at com.wecanendcraving.encryption.MainApp.main(MainApp.java:53)
```

**Comment by Perflyst** [comment]
Well okay, if I use 3 AES 256 keys it works, but is it not possible to merge only two?

**Comment by Perflyst** [comment]
patch for anyone who just wants to merge two

```
diff --git a/src/main/java/com/wecanendcraving/encryption/MainApp.java b/src/main/java/com/wecanendcraving/encryption/MainApp.java
index cb7893c..df812f4 100644
--- a/src/main/java/com/wecanendcraving/encryption/MainApp.java
+++ b/src/main/java/com/wecanendcraving/encryption/MainApp.java
@@ -50,12 +50,9 @@ public class MainApp {
                        byte[] decodedKey2 = BaseEncoding.base16().decode(args[2]);
                        // rebuild key using SecretKeySpec
                        SecretKey originalDecodedKey2 = new SecretKeySpec(decodedKey2, 0, decodedKey2.length, "AES"); 
-                       byte[] decodedKey3 = BaseEncoding.base16().decode(args[3]);
-                       // rebuild key using SecretKeySpec
-                       SecretKey originalDecodedKey3 = new SecretKeySpec(decodedKey3, 0, decodedKey3.length, "AES");
                        byte[] finalAESKey= new byte[originalDecodedKey1.getEncoded().length];
                        while (y < originalDecodedKey1.getEncoded().length){
-                               finalAESKey[y] = (byte) (originalDecodedKey1.getEncoded()[y] ^ originalDecodedKey2.getEncoded()[y] ^ originalDecodedKey3.getEncoded()[y]);
+                               finalAESKey[y] = (byte) (originalDecodedKey1.getEncoded()[y] ^ originalDecodedKey2.getEncoded()[y]);
                                ++y;
                        }
                        showKey(finalAESKey);
```
